Repository GNYniamh/The_Library, pull requests merged in 2024-10, with the labels that each got.

#8 Add CODE_OF_CONDUCT file to the Project
  CODE_OF_CONDUCT.md
Labels: hacktoberfest

#9 Adding web fundamentals to library
  Fundamentals/Web Fundamentals
Labels: documentation, hacktoberfest

#10 Overview file for curl usage
  Fundamentals/curl
Labels: documentation, hacktoberfest

#11 Create OSINT Toolbox
  OSINT/Toolbox
Labels: enhancement, hacktoberfest
